"""create tables

Revision ID: 38eaee0d936c
Revises: 
Create Date: 2026-05-11 11:08:30.636698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38eaee0d936c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BOOKINGS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=30), nullable=False),
    sa.Column('train_name', sa.String(length=100), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('from_station_id', sa.Integer(), nullable=True),
    sa.Column('to_station_id', sa.Integer(), nullable=True),
    sa.Column('from_station_sequence_number', sa.Integer(), nullable=True),
    sa.Column('to_station_sequence_number', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('payment_order_id', sa.Integer(), nullable=True),
    sa.Column('locked_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SEATS_HELD', 'PAYMENT_PENDING', 'CONFIRMING', 'CONFIRMED', 'CANCELLING', 'FAILED', 'CANCELLED', 'EXPIRED', name='booking_status_enum'), server_default='PENDING', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_idempotencyKey'),
    sa.UniqueConstraint('payment_order_id', name='uq_paymentOrderId')
    )
    op.create_table('BOOKING_PASSENGERS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Transgender', 'Other', name='gender_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='status_enum'), server_default='ACTIVE', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BOOKING_SAGA_LOGS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('saga_step', sa.Enum('HOLD_SEATS', 'CREATE_PAYMENT', 'CONFIRM_SEATS', 'COMPLETE', name='saga_step_enum'), server_default='HOLD_SEATS', nullable=False),
    sa.Column('request', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'COMPENSATING', 'COMPENSATED', 'FAILED', name='status_enum'), server_default='PENDING', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('BOOKING_SEATS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_type', sa.Enum('LOWER', 'MIDDLE', 'UPPER', 'SIDE_LOWER', 'SIDE_UPPER', name='seat_type_enum'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='status_enum'), server_default='ACTIVE', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', 'seat_id', name='uq_bookingIdSeatId')
    )
    op.create_table('IDEMPOTENCY_RECORDS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_key', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('event_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_key', name='uq_eventKey')
    )
    op.create_table('OTP_CHALLENGES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('destination_masked', sa.String(length=120), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('otp_ciphertext', sa.Text(), nullable=False),
    sa.Column('cipher_key_version', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('attempts_used', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', name='uq_otp_challenges_challenge_id')
    )
    op.create_index('ix_otp_challenges_expires_at', 'OTP_CHALLENGES', ['expires_at'], unique=False)
    op.create_index('ix_otp_challenges_user_purpose_status', 'OTP_CHALLENGES', ['user_id', 'purpose', 'status'], unique=False)
    op.create_table('OUTBOX_EVENTS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'aggregate_id', name='uq_outbox_event_aggregate')
    )
    op.create_index('ix_outbox_events_created_at', 'OUTBOX_EVENTS', ['created_at'], unique=False)
    op.create_index('ix_outbox_events_status_next_retry', 'OUTBOX_EVENTS', ['status', 'next_retry_at'], unique=False)
    op.create_table('PAYMENT_AUDIT_LOGS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_order_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('gateway_response', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), server_default='A', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PAYMENT_ORDERS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('currency', sa.String(length=30), server_default='INR', nullable=False),
    sa.Column('gateway_provider', sa.String(length=30), server_default='razorpay', nullable=False),
    sa.Column('gateway_order_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_payment_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_signature', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'CAPTURED', 'REFUND_INITIATED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'FAILED', 'CANCELLED', 'EXPIRED', name='status_enum'), server_default='CREATED', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_order_id', name='uq_gatewayOrderId'),
    sa.UniqueConstraint('gateway_payment_id', name='uq_paymentOrderId'),
    sa.UniqueConstraint('idempotency_key', name='uq_idempotencyKey')
    )
    op.create_table('REFUND_ORDERS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('payment_order_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('gateway_refund_id', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED', name='status_enum'), server_default='INITIATED', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_refund_id', name='uq_gatewayRefundId'),
    sa.UniqueConstraint('idempotency_key', name='uq_idempotencyKey')
    )
    op.create_table('ROUTES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), server_default='A', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', name='uq_trainId')
    )
    op.create_index('ix_status', 'ROUTES', ['status'], unique=False)
    op.create_table('ROUTE_STATIONS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('distance_from_origin', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), server_default='A', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence_number', name='uq_routeIdSeqNumber'),
    sa.UniqueConstraint('route_id', 'station_id', name='uq_routeIdStationId')
    )
    op.create_index('ix_status', 'ROUTE_STATIONS', ['status'], unique=False)
    op.create_table('ROUTE_STOP',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(length=150), nullable=False),
    sa.Column('station_code', sa.String(length=20), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='route_stop_status'), server_default='ACTIVE', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'sequence_number', name='uq_scheduleIdSequenceNumber'),
    sa.UniqueConstraint('schedule_id', 'station_id', name='uq_scheduleIdStationId')
    )
    op.create_table('SCHEDULES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), server_default='A', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'departure_date', name='uq_trainIdDepartureDate')
    )
    op.create_index('ix_status', 'SCHEDULES', ['status'], unique=False)
    op.create_table('SCHEDULE_INVENTORY',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('train_number', sa.String(length=30), nullable=False),
    sa.Column('train_name', sa.String(length=100), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('total_seats', sa.Integer(), server_default='0', nullable=False),
    sa.Column('available_seats', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('booked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'CANCELLED', name='schedule_inventory_status_enum'), server_default='ACTIVE', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', name='uq_scheduledId')
    )
    op.create_table('SEATS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_type', sa.Enum('LOWER', 'MIDDLE', 'UPPER', 'SIDE_LOWER', 'SIDE_UPPER', name='seat_type_enum'), server_default='LOWER', nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), server_default='A', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'seat_number', name='uq_trainIdSeatNumber')
    )
    op.create_index('ix_status', 'SEATS', ['status'], unique=False)
    op.create_table('SEAT_INVENTORY',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_inventory_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_type', sa.Enum('LOWER', 'MIDDLE', 'UPPER', 'SIDE_LOWER', 'SIDE_UPPER', name='seat_type_enum'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'LOCKED', 'BOOKED', 'CANCELLED', name='seat_inventory_status_enum'), server_default='AVAILABLE', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'seat_id', name='uq_scheduleIdSeatId'),
    sa.UniqueConstraint('schedule_id', 'seat_number', name='uq_scheduleIdSeatNumber')
    )
    op.create_table('SEAT_SEGMENT_LOCK',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('seat_id', sa.Integer(), nullable=False),
    sa.Column('from_station_sequence_number', sa.Integer(), nullable=False),
    sa.Column('to_station_sequence_number', sa.Integer(), nullable=False),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'LOCKED', 'BOOKED', 'CANCELLED', name='seat_segement_status_enum'), server_default='AVAILABLE', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SECURITY_EVENT_LOG',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('event_category', sa.String(length=60), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_event_correlation_id', 'SECURITY_EVENT_LOG', ['correlation_id'], unique=False)
    op.create_index('ix_security_event_name_created', 'SECURITY_EVENT_LOG', ['event_name', 'created_at'], unique=False)
    op.create_index('ix_security_event_user_created', 'SECURITY_EVENT_LOG', ['user_id', 'created_at'], unique=False)
    op.create_table('STATIONS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), server_default='A', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_code')
    )
    op.create_index('ix_code', 'STATIONS', ['code'], unique=False)
    op.create_index('ix_name', 'STATIONS', ['name'], unique=False)
    op.create_index('ix_status', 'STATIONS', ['status'], unique=False)
    op.create_table('TRAINS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_number', sa.String(length=30), nullable=False),
    sa.Column('train_name', sa.String(length=100), nullable=False),
    sa.Column('coach_name', sa.String(length=10), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), server_default='A', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_number', name='uq_trainNumber')
    )
    op.create_index('ix_status', 'TRAINS', ['status'], unique=False)
    op.create_table('USERS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('is_mobile_verified', sa.Enum('Y', 'N', name='mobile_verified_enum'), nullable=False),
    sa.Column('mobile_verified_last_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('is_email_verified', sa.Enum('Y', 'N', name='email_verified_enum'), nullable=False),
    sa.Column('email_verified_last_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Transgender', name='gender_enum'), nullable=False),
    sa.Column('profile', sa.Enum('User', 'Admin', 'Guest', name='profile_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('USER_TOKENS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_tokens_user_status_revoked', 'USER_TOKENS', ['user_id', 'status', 'revoked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tokens_user_status_revoked', table_name='USER_TOKENS')
    op.drop_table('USER_TOKENS')
    op.drop_table('USERS')
    op.drop_index('ix_status', table_name='TRAINS')
    op.drop_table('TRAINS')
    op.drop_index('ix_status', table_name='STATIONS')
    op.drop_index('ix_name', table_name='STATIONS')
    op.drop_index('ix_code', table_name='STATIONS')
    op.drop_table('STATIONS')
    op.drop_index('ix_security_event_user_created', table_name='SECURITY_EVENT_LOG')
    op.drop_index('ix_security_event_name_created', table_name='SECURITY_EVENT_LOG')
    op.drop_index('ix_security_event_correlation_id', table_name='SECURITY_EVENT_LOG')
    op.drop_table('SECURITY_EVENT_LOG')
    op.drop_table('SEAT_SEGMENT_LOCK')
    op.drop_table('SEAT_INVENTORY')
    op.drop_index('ix_status', table_name='SEATS')
    op.drop_table('SEATS')
    op.drop_table('SCHEDULE_INVENTORY')
    op.drop_index('ix_status', table_name='SCHEDULES')
    op.drop_table('SCHEDULES')
    op.drop_table('ROUTE_STOP')
    op.drop_index('ix_status', table_name='ROUTE_STATIONS')
    op.drop_table('ROUTE_STATIONS')
    op.drop_index('ix_status', table_name='ROUTES')
    op.drop_table('ROUTES')
    op.drop_table('REFUND_ORDERS')
    op.drop_table('PAYMENT_ORDERS')
    op.drop_table('PAYMENT_AUDIT_LOGS')
    op.drop_index('ix_outbox_events_status_next_retry', table_name='OUTBOX_EVENTS')
    op.drop_index('ix_outbox_events_created_at', table_name='OUTBOX_EVENTS')
    op.drop_table('OUTBOX_EVENTS')
    op.drop_index('ix_otp_challenges_user_purpose_status', table_name='OTP_CHALLENGES')
    op.drop_index('ix_otp_challenges_expires_at', table_name='OTP_CHALLENGES')
    op.drop_table('OTP_CHALLENGES')
    op.drop_table('IDEMPOTENCY_RECORDS')
    op.drop_table('BOOKING_SEATS')
    op.drop_table('BOOKING_SAGA_LOGS')
    op.drop_table('BOOKING_PASSENGERS')
    op.drop_table('BOOKINGS')
    # ### end Alembic commands ###
