"""create tables

Revision ID: 8787f589fbd6
Revises: 
Create Date: 2026-04-26 16:10:20.410720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8787f589fbd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OTP_CHALLENGES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('destination_masked', sa.String(length=120), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('otp_ciphertext', sa.Text(), nullable=False),
    sa.Column('cipher_key_version', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('attempts_used', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', name='uq_otp_challenges_challenge_id')
    )
    op.create_index('ix_otp_challenges_expires_at', 'OTP_CHALLENGES', ['expires_at'], unique=False)
    op.create_index('ix_otp_challenges_user_purpose_status', 'OTP_CHALLENGES', ['user_id', 'purpose', 'status'], unique=False)
    op.create_table('OUTBOX_EVENTS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'aggregate_id', name='uq_outbox_event_aggregate')
    )
    op.create_index('ix_outbox_events_created_at', 'OUTBOX_EVENTS', ['created_at'], unique=False)
    op.create_index('ix_outbox_events_status_next_retry', 'OUTBOX_EVENTS', ['status', 'next_retry_at'], unique=False)
    op.create_table('ROUTES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', name='uq_trainId')
    )
    op.create_index('ix_status', 'ROUTES', ['status'], unique=False)
    op.create_table('ROUTE_STATIONS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('distance_from_origin', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'sequence_number', name='uq_routeId_seqNumber'),
    sa.UniqueConstraint('route_id', 'station_id', name='uq_routeId_stationId')
    )
    op.create_index('ix_status', 'ROUTE_STATIONS', ['status'], unique=False)
    op.create_table('SCHEDULES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'departure_date', name='uq_trainId_depDate')
    )
    op.create_index('ix_status', 'SCHEDULES', ['status'], unique=False)
    op.create_table('SEATS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_type', sa.Enum('LOWER', 'MIDDLE', 'UPPER', 'SIDE_LOWER', 'SIDE_UPPER', name='seat_type_enum'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'seat_number', name='uq_trainId_seatNumber')
    )
    op.create_index('ix_status', 'SEATS', ['status'], unique=False)
    op.create_table('SECURITY_EVENT_LOG',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('event_category', sa.String(length=60), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_event_correlation_id', 'SECURITY_EVENT_LOG', ['correlation_id'], unique=False)
    op.create_index('ix_security_event_name_created', 'SECURITY_EVENT_LOG', ['event_name', 'created_at'], unique=False)
    op.create_index('ix_security_event_user_created', 'SECURITY_EVENT_LOG', ['user_id', 'created_at'], unique=False)
    op.create_table('STATIONS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_code')
    )
    op.create_index('ix_code', 'STATIONS', ['code'], unique=False)
    op.create_index('ix_name', 'STATIONS', ['name'], unique=False)
    op.create_index('ix_status', 'STATIONS', ['status'], unique=False)
    op.create_table('TRAINS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('train_number', sa.String(length=30), nullable=False),
    sa.Column('train_name', sa.String(length=100), nullable=False),
    sa.Column('coach_name', sa.String(length=10), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_number', name='uq_train_number')
    )
    op.create_index('ix_status', 'TRAINS', ['status'], unique=False)
    op.create_table('USERS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('is_mobile_verified', sa.Enum('Y', 'N', name='mobile_verified_enum'), nullable=False),
    sa.Column('mobile_verified_last_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('is_email_verified', sa.Enum('Y', 'N', name='email_verified_enum'), nullable=False),
    sa.Column('email_verified_last_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Transgender', name='gender_enum'), nullable=False),
    sa.Column('profile', sa.Enum('User', 'Admin', 'Guest', name='profile_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('USER_TOKENS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('A', 'Z', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_tokens_user_status_revoked', 'USER_TOKENS', ['user_id', 'status', 'revoked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_tokens_user_status_revoked', table_name='USER_TOKENS')
    op.drop_table('USER_TOKENS')
    op.drop_table('USERS')
    op.drop_index('ix_status', table_name='TRAINS')
    op.drop_table('TRAINS')
    op.drop_index('ix_status', table_name='STATIONS')
    op.drop_index('ix_name', table_name='STATIONS')
    op.drop_index('ix_code', table_name='STATIONS')
    op.drop_table('STATIONS')
    op.drop_index('ix_security_event_user_created', table_name='SECURITY_EVENT_LOG')
    op.drop_index('ix_security_event_name_created', table_name='SECURITY_EVENT_LOG')
    op.drop_index('ix_security_event_correlation_id', table_name='SECURITY_EVENT_LOG')
    op.drop_table('SECURITY_EVENT_LOG')
    op.drop_index('ix_status', table_name='SEATS')
    op.drop_table('SEATS')
    op.drop_index('ix_status', table_name='SCHEDULES')
    op.drop_table('SCHEDULES')
    op.drop_index('ix_status', table_name='ROUTE_STATIONS')
    op.drop_table('ROUTE_STATIONS')
    op.drop_index('ix_status', table_name='ROUTES')
    op.drop_table('ROUTES')
    op.drop_index('ix_outbox_events_status_next_retry', table_name='OUTBOX_EVENTS')
    op.drop_index('ix_outbox_events_created_at', table_name='OUTBOX_EVENTS')
    op.drop_table('OUTBOX_EVENTS')
    op.drop_index('ix_otp_challenges_user_purpose_status', table_name='OTP_CHALLENGES')
    op.drop_index('ix_otp_challenges_expires_at', table_name='OTP_CHALLENGES')
    op.drop_table('OTP_CHALLENGES')
    # ### end Alembic commands ###
