"""create others required tables

Revision ID: f20372040935
Revises: be78612396d7
Create Date: 2026-03-16 09:34:24.947027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20372040935'
down_revision: Union[str, Sequence[str], None] = 'be78612396d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('OTP_CHALLENGES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('destination_masked', sa.String(length=120), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('otp_ciphertext', sa.Text(), nullable=False),
    sa.Column('cipher_key_version', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('attempts_used', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', name='uq_otp_challenges_challenge_id')
    )
    op.create_index('ix_otp_challenges_expires_at', 'OTP_CHALLENGES', ['expires_at'], unique=False)
    op.create_index('ix_otp_challenges_user_purpose_status', 'OTP_CHALLENGES', ['user_id', 'purpose', 'status'], unique=False)
    op.create_table('OUTBOX_EVENTS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('aggregate_type', sa.String(length=50), nullable=False),
    sa.Column('aggregate_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type', 'aggregate_id', name='uq_outbox_event_aggregate')
    )
    op.create_index('ix_outbox_events_created_at', 'OUTBOX_EVENTS', ['created_at'], unique=False)
    op.create_index('ix_outbox_events_status_next_retry', 'OUTBOX_EVENTS', ['status', 'next_retry_at'], unique=False)
    op.create_table('SECURITY_EVENT_LOG',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=80), nullable=False),
    sa.Column('event_category', sa.String(length=60), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('reason_code', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_event_correlation_id', 'SECURITY_EVENT_LOG', ['correlation_id'], unique=False)
    op.create_index('ix_security_event_name_created', 'SECURITY_EVENT_LOG', ['event_name', 'created_at'], unique=False)
    op.create_index('ix_security_event_user_created', 'SECURITY_EVENT_LOG', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_security_event_user_created', table_name='SECURITY_EVENT_LOG')
    op.drop_index('ix_security_event_name_created', table_name='SECURITY_EVENT_LOG')
    op.drop_index('ix_security_event_correlation_id', table_name='SECURITY_EVENT_LOG')
    op.drop_table('SECURITY_EVENT_LOG')
    op.drop_index('ix_outbox_events_status_next_retry', table_name='OUTBOX_EVENTS')
    op.drop_index('ix_outbox_events_created_at', table_name='OUTBOX_EVENTS')
    op.drop_table('OUTBOX_EVENTS')
    op.drop_index('ix_otp_challenges_user_purpose_status', table_name='OTP_CHALLENGES')
    op.drop_index('ix_otp_challenges_expires_at', table_name='OTP_CHALLENGES')
    op.drop_table('OTP_CHALLENGES')
    # ### end Alembic commands ###
